name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tmate:
        type: boolean
        description: 'SSH debug'
        required: false
        default: false

permissions:
  packages: write
  contents: write

env:
  CCACHE_DIR: "/dev/shm/ccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate }}
        with:
          detached: true

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/var/pmbootstrap
            ../pmbootstrap
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          set -x
          # https://packages.ubuntu.com/plucky/pmbootstrap : git kpartx openssl python3
          #sudo apt-get install git kpartx openssl python3

          cd ..
          if [ -d pmbootstrap ]; then
            git -C pmbootstrap pull
          else
            git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git pmbootstrap
          fi
          PMB="`pwd`/pmbootstrap/pmbootstrap.py --details-to-stdout -y"

          yes '' | $PMB --details-to-stdout init
          $PMB work_migrate
          $PMB -q shutdown

      # https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/blob/b982e45c8d1c803360e1d8227cf88c5a4c607979/.gitlab-ci.yml
      # https://gitlab.postmarketos.org/postmarketOS/build.postmarketos.org/-/blob/bd94e26981da2b44020db26e2d2f1d994194de2c/bpo/jobs/build_image.py
      - name: Build
        run: |
          PMB="`pwd`/../pmbootstrap/pmbootstrap.py --details-to-stdout -y"

          ln -s `pwd` /home/runner/.local/var/pmbootstrap/cache_git/pmaports/device/blade10
          # hack: Are symlinks referenced based on the source of Symlink?
          ln -s ~/.local/var/pmbootstrap/cache_git/pmaports/device/.shared-patches/ ..

          set -x

          $PMB config device lenovo-b8000
          $PMB config ui fbkeyboard
          $PMB install --password 147147
          $PMB install --password 147147 --android-recovery-zip
          # https://wiki.postmarketos.org/wiki/Installation_from_recovery_mode
          $PMB export

      - name: Release
        run: |
          pushd /tmp/postmarketOS-export/
          # pmbootstrap creates symlinks to non-existent files
          find . -type l -print0 | while IFS= read -r -d $'\0' symlink; do
            target=$(readlink "$symlink")
            if [ ! -e "$target" ]; then
              rm "$symlink"
            fi
          done

          popd
          gh release create "build-$(date +%Y-%m-%d-%H-%M-%S)" '/tmp/postmarketOS-export/*'

        env:
          GH_TOKEN: ${{ github.token }}
