name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tmate:
        type: boolean
        description: 'SSH debug'
        required: false
        default: false

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate }}
        with:
          detached: true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/var/pmbootstrap
          # /home/runner/work/lenovo-b8000_postmarketos_files/pmbootstrap
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          set -x
          cat >> /etc/sudoers << EOL
          root ALL=(ALL:ALL) NOPASSWD: ALL
          builder ALL=(ALL:ALL) NOPASSWD: ALL
          EOL
          pacman -Syu --noconfirm pmbootstrap sudo
          # https://packages.ubuntu.com/plucky/pmbootstrap : git kpartx openssl python3
          #sudo apt-get install git kpartx openssl python3

          #cd ..
          #if [ -d pmbootstrap ]; then
          #  git -C pmbootstrap pull
          #else
          #  git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git pmbootstrap
          #fi
          #PMB="`pwd`/pmbootstrap/pmbootstrap.py --details-to-stdout -y"
          useradd -m builder

          << EOF sudo -u builder sh
            PMB="pmbootstrap --details-to-stdout -y"
            yes '' | $PMB --details-to-stdout init
            $PMB work_migrate
            $PMB -q shutdown
          EOL

      - name: Build
        run: |
          << EOF sudo -u builder sh
            # https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/blob/b982e45c8d1c803360e1d8227cf88c5a4c607979/.gitlab-ci.yml
            # https://gitlab.postmarketos.org/postmarketOS/build.postmarketos.org/-/blob/bd94e26981da2b44020db26e2d2f1d994194de2c/bpo/jobs/build_image.py
            set -x
            #PMB="`pwd`/../pmbootstrap/pmbootstrap.py --details-to-stdout -y"
            PMB="pmbootstrap --details-to-stdout -y"

            TARGET_DIR="/home/runner/.local/var/pmbootstrap/cache_git/pmaports/device/testing"
            for dir in */; do
              ln -f -s -v -n "$(pwd)/${dir%/}" "$TARGET_DIR"
            done

            $PMB config device lenovo-b8000
            $PMB config ui fbkeyboard
            $PMB install --password 147147
            #$PMB install --password 147147 --android-recovery-zip
            # https://wiki.postmarketos.org/wiki/Installation_from_recovery_mode
            $PMB export
          EOL

      - name: Release
        run: |
          pushd /tmp/postmarketOS-export/
          # pmbootstrap creates symlinks to non-existent files
          find . -type l -print0 | while IFS= read -r -d $'\0' symlink; do
            target=$(readlink "$symlink")
            if [ ! -e "$target" ]; then
              rm "$symlink"
            fi
          done

          popd
          gh release create "build-${{ github.ref_name }}-$(date +%Y-%m-%d-%H-%M-%S)" '/tmp/postmarketOS-export/*'

        env:
          GH_TOKEN: ${{ github.token }}
